sudo: false

language: c

compiler:
  - gcc

script: ./configure --enable-single-host && make -j2 from-scratch && make check && make clean && ./configure --enable-single-host --enable-cplusplus && make -j2 && make check && make clean && ./configure --enable-ansi-c && make -j2 && (cd tests; make test1) && (cd tests; make test2) && (cd tests; make test3) && (cd tests; make test4) && (cd tests; make test5)

notifications:
  webhooks:
    urls: https://webhooks.gitter.im/e/ddbe4ac173b7fa2b4bed
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
