(declare (extended-bindings) (not constant-fold) (not safe))

(define f (##not 123))
(define t (##not f))
(define s "")
(define x 1.5)
(define y (##make-vector 2 999))
(define z (##list 1 2 3))
(define a 'a)
(define b (quote b))
(define c (##make-uninterned-symbol "uninterned" 80))

(define (test x)
  (println (##symbol? x))
  (println (if (##symbol? x) "symbol" "not symbol")))

(test 0)
(test 1)
(test f)
(test t)
(test s)
(test x)
(test y)
(test z)
(test a)
(test b)
(test c)
(test (##cdr z))

;(println (##values-ref w 0))
;(println (##values-ref w 1))
;(##values-set! w 1 888)
;(println (##values-ref w 1))
