(declare (extended-bindings) (not constant-fold) (not safe))

(define s1 (##bignum.make 3 #f #f))
(define s2 (##bignum.make 3 #f #t))

(define (test2 x y)
  ;(println (or x y))
  (println (if (or x y) 11 22))
  ;(println (or (##not x) y))
  (println (if (or (##not x) y) 11 22))
  ;(println (or x (##not y)))
  (println (if (or x (##not y)) 11 22))
  (println (or (##not x) (##not y)))
  (println (if (or (##not x) (##not y)) 11 22))
  (println (##not (or x y)))
  (println (if (##not (or x y)) 11 22))
  (println (##not (or (##not x) y)))
  (println (if (##not (or (##not x) y)) 11 22))
  (println (##not (or x (##not y))))
  (println (if (##not (or x (##not y))) 11 22))
  (println (##not (or (##not x) (##not y))))
  (println (if (##not (or (##not x) (##not y))) 11 22)))

(define (test x)
  (test2 x s1)
  (test2 x s2))

(test s1)
(test s2)
